on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual trigger

name: pkgdown

jobs:
  pkgdown:
    runs-on: macos-latest  # macOS for faster R builds
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-key: true

      - uses: r-lib/actions/r-check@v2
        with:
          build-args: 'cflags=-Wall'
          extra-checks: '"copyrights"'
          check-args: '--as-cran'

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("pkgdown")

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs